---
version: 1
phases:
  install:
    runtime-versions:
      nodejs: 16.x
    commands:
      - npm cl
  build:
    commands:
      - npm run build
    artifacts:
      files:
        - "**/*"
      base-directory: build
cache:
  - paths:
      - node_modules/**/*
